import { pgTable, text, timestamp, serial, boolean, time, integer, unique } from "drizzle-orm/pg-core"
import { profiles } from "./profiles"
import { linkedinProfiles } from "./linkedin-profiles"

export const schedulingConfigs = pgTable("scheduling_configs", {
  id: serial("id").primaryKey(),
  userId: text("user_id").references(() => profiles.id, { onDelete: "cascade" }),
  linkedinProfileId: serial("linkedin_profile_id").references(() => linkedinProfiles.id, { onDelete: "cascade" }),
  enabled: boolean("enabled").default(true),
  timezone: text("timezone").default("America/Mexico_City"),
  mondayEnabled: boolean("monday_enabled").default(true),
  mondayStartTime: text("monday_start_time").default("09:00"),
  mondayEndTime: text("monday_end_time").default("17:00"),
  mondayPostsCount: integer("monday_posts_count").default(3),
  tuesdayEnabled: boolean("tuesday_enabled").default(true),
  tuesdayStartTime: text("tuesday_start_time").default("09:00"),
  tuesdayEndTime: text("tuesday_end_time").default("17:00"),
  tuesdayPostsCount: integer("tuesday_posts_count").default(3),
  wednesdayEnabled: boolean("wednesday_enabled").default(true),
  wednesdayStartTime: text("wednesday_start_time").default("09:00"),
  wednesdayEndTime: text("wednesday_end_time").default("17:00"),
  wednesdayPostsCount: integer("wednesday_posts_count").default(3),
  thursdayEnabled: boolean("thursday_enabled").default(true),
  thursdayStartTime: text("thursday_start_time").default("09:00"),
  thursdayEndTime: text("thursday_end_time").default("17:00"),
  thursdayPostsCount: integer("thursday_posts_count").default(3),
  fridayEnabled: boolean("friday_enabled").default(true),
  fridayStartTime: text("friday_start_time").default("09:00"),
  fridayEndTime: text("friday_end_time").default("17:00"),
  fridayPostsCount: integer("friday_posts_count").default(3),
  saturdayEnabled: boolean("saturday_enabled").default(false),
  saturdayStartTime: text("saturday_start_time").default("10:00"),
  saturdayEndTime: text("saturday_end_time").default("14:00"),
  saturdayPostsCount: integer("saturday_posts_count").default(1),
  sundayEnabled: boolean("sunday_enabled").default(false),
  sundayStartTime: text("sunday_start_time").default("10:00"),
  sundayEndTime: text("sunday_end_time").default("14:00"),
  sundayPostsCount: integer("sunday_posts_count").default(1),
  autoGenerateContent: boolean("auto_generate_content").default(true),
  includeHashtags: boolean("include_hashtags").default(true),
  includeSummary: boolean("include_summary").default(true),
  includeImage: boolean("include_image").default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => [
  unique().on(t.userId, t.linkedinProfileId),
])
