-- Script SQL para configurar la base de datos en Supabase
-- Ejecutar este script en el SQL Editor de Supabase

-- Habilitar extensiones útiles
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- Para encriptación
CREATE EXTENSION IF NOT EXISTS pg_trgm;   -- Para búsquedas de texto

-- Tabla de usuarios (extensión de auth.users de Supabase)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  username TEXT UNIQUE,
  avatar_url TEXT,
  role TEXT CHECK (role IN ('admin', 'user')) DEFAULT 'user',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_profiles_role ON profiles(role);

-- Tabla de categorías de noticias
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  rss_feed_url TEXT,
  newsapi_category TEXT,  -- Ej. 'technology', 'business' para NewsAPI
  provider_type TEXT DEFAULT 'newsapi',  -- Ej. 'newsapi', 'rss', 'custom'
  api_key_encrypted TEXT,  -- Encriptado para creds de portales
  usage_count INTEGER DEFAULT 0,  -- Calls por día para monitoreo
  is_active BOOLEAN DEFAULT TRUE,
  created_by UUID REFERENCES profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_categories_active ON categories(is_active);
CREATE INDEX idx_categories_provider ON categories(provider_type);

-- Tabla de perfiles de LinkedIn
CREATE TABLE linkedin_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) NOT NULL,
  profile_name TEXT NOT NULL,
  linkedin_id TEXT NOT NULL,
  access_token TEXT NOT NULL,  -- Encriptar en producción: pgp_sym_encrypt(access_token, 'key')
  refresh_token TEXT,  -- Encriptar también
  token_expires_at TIMESTAMP WITH TIME ZONE,
  profile_type TEXT CHECK (profile_type IN ('personal', 'company')) DEFAULT 'personal',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_linkedin_user ON linkedin_profiles(user_id);

-- Tabla de relación perfiles-categorías
CREATE TABLE profile_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id BIGINT REFERENCES linkedin_profiles(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(profile_id, category_id)
);

-- Tabla de noticias
CREATE TABLE news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES categories(id) NOT NULL,
  title TEXT NOT NULL,
  summary TEXT,  -- Resumen original de fuente
  ai_summary TEXT,  -- Resumen generado por IA (estandarizado)
  content TEXT,
  source_url TEXT NOT NULL,
  image_url TEXT,  -- Imagen original de fuente
  ai_image_url TEXT,  -- Imagen generada por IA, almacenada en Supabase Storage
  source_name TEXT,
  published_at TIMESTAMP WITH TIME ZONE,
  is_processed BOOLEAN DEFAULT FALSE,  -- Flag para IA completada
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_news_category ON news(category_id);
CREATE INDEX idx_news_processed ON news(is_processed);
CREATE INDEX idx_news_published ON news(published_at DESC);  -- Para noticias recientes
CREATE INDEX idx_news_title ON news USING gin(title gin_trgm_ops);  -- Búsqueda de texto

-- Tabla de publicaciones programadas
CREATE TABLE scheduled_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id BIGINT REFERENCES linkedin_profiles(id) NOT NULL,
  post_content TEXT NOT NULL,  -- Compilación: intro + resúmenes + calls to action
  image_url TEXT,  -- Imagen principal (de una noticia o generada)
  scheduled_time TIMESTAMP WITH TIME ZONE NOT NULL,
  status TEXT CHECK (status IN ('pending', 'published', 'failed', 'retrying')) DEFAULT 'pending',
  posted_at TIMESTAMP WITH TIME ZONE,
  linkedin_post_id TEXT,  -- ID del post en LinkedIn para tracking
  error_message TEXT,  -- Para fallos
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_scheduled_time ON scheduled_posts(scheduled_time);
CREATE INDEX idx_scheduled_status ON scheduled_posts(status);

-- Tabla de relación publicaciones-noticias
CREATE TABLE post_news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES scheduled_posts(id) ON DELETE CASCADE,
  news_id BIGINT REFERENCES news(id) ON DELETE CASCADE,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de audits para logs
CREATE TABLE audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id),
  action TEXT NOT NULL,  -- Ej. 'post_published', 'news_fetched'
  details JSONB,  -- Datos flexibles
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_audits_action ON audits(action);
CREATE INDEX idx_audits_created ON audits(created_at DESC);

-- Habilitar Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE linkedin_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE profile_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE news ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_news ENABLE ROW LEVEL SECURITY;
ALTER TABLE audits ENABLE ROW LEVEL SECURITY;

-- Políticas de seguridad para profiles
CREATE POLICY "Users can view their own profile" ON profiles
  FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins can view all profiles" ON profiles
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Políticas para categories (lectura pública, escritura solo admins)
CREATE POLICY "Anyone can view active categories" ON categories
  FOR SELECT USING (is_active = true);
CREATE POLICY "Admins manage categories" ON categories
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Políticas para linkedin_profiles
CREATE POLICY "Users can view their own LinkedIn profiles" ON linkedin_profiles
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own LinkedIn profiles" ON linkedin_profiles
  FOR ALL USING (auth.uid() = user_id);

-- Políticas para profile_categories
CREATE POLICY "Users can manage their own profile categories" ON profile_categories
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM linkedin_profiles 
      WHERE id = profile_categories.profile_id 
      AND user_id = auth.uid()
    )
  );

-- Políticas para news (lectura pública)
CREATE POLICY "Anyone can view processed news" ON news
  FOR SELECT USING (is_processed = true);

-- Políticas para scheduled_posts
CREATE POLICY "Users can view their own scheduled posts" ON scheduled_posts
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM linkedin_profiles 
      WHERE id = scheduled_posts.profile_id 
      AND user_id = auth.uid()
    )
  );
CREATE POLICY "Users can manage their own scheduled posts" ON scheduled_posts
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM linkedin_profiles 
      WHERE id = scheduled_posts.profile_id 
      AND user_id = auth.uid()
    )
  );

-- Políticas para post_news
CREATE POLICY "Users can manage their own post news" ON post_news
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM scheduled_posts sp
      JOIN linkedin_profiles lp ON sp.profile_id = lp.id
      WHERE sp.id = post_news.post_id 
      AND lp.user_id = auth.uid()
    )
  );

-- Políticas para audits
CREATE POLICY "Users can insert audits" ON audits FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins view all audits" ON audits FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Función para actualizar updated_at automáticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers para updated_at
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_categories_updated_at BEFORE UPDATE ON categories
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_linkedin_profiles_updated_at BEFORE UPDATE ON linkedin_profiles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_news_updated_at BEFORE UPDATE ON news
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_scheduled_posts_updated_at BEFORE UPDATE ON scheduled_posts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insertar categorías por defecto
INSERT INTO categories (name, description, newsapi_category, provider_type, is_active) VALUES
('Tecnología', 'Noticias sobre tecnología, startups y innovación', 'technology', 'newsapi', true),
('Negocios', 'Noticias empresariales y financieras', 'business', 'newsapi', true),
('Finanzas', 'Mercados financieros y economía', 'business', 'newsapi', true),
('Salud', 'Noticias sobre salud y medicina', 'health', 'newsapi', true),
('Ciencia', 'Avances científicos y investigación', 'science', 'newsapi', true);

-- Función para crear perfil automáticamente al registrarse
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, role)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)), 'user');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger para crear perfil automáticamente
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Configurar Storage para imágenes
INSERT INTO storage.buckets (id, name, public) VALUES ('ai-images', 'ai-images', true);
INSERT INTO storage.buckets (id, name, public) VALUES ('news-images', 'news-images', true);

-- Políticas para Storage
CREATE POLICY "Public read access for ai-images" ON storage.objects
FOR SELECT USING (bucket_id = 'ai-images');

CREATE POLICY "Public read access for news-images" ON storage.objects
FOR SELECT USING (bucket_id = 'news-images');

-- Función para obtener estadísticas del admin
CREATE OR REPLACE FUNCTION get_admin_stats(period_days INTEGER DEFAULT 7)
RETURNS JSON AS $$
DECLARE
  result JSON;
BEGIN
  SELECT json_build_object(
    'total_users', (SELECT COUNT(*) FROM profiles),
    'active_users', (SELECT COUNT(*) FROM profiles WHERE updated_at > NOW() - INTERVAL '7 days'),
    'total_posts_published', (SELECT COUNT(*) FROM scheduled_posts WHERE status = 'published' AND created_at > NOW() - (period_days || ' days')::INTERVAL),
    'posts_failed', (SELECT COUNT(*) FROM scheduled_posts WHERE status = 'failed' AND created_at > NOW() - (period_days || ' days')::INTERVAL),
    'error_rate', (
      CASE 
        WHEN (SELECT COUNT(*) FROM scheduled_posts WHERE created_at > NOW() - (period_days || ' days')::INTERVAL) > 0 
        THEN ROUND(
          (SELECT COUNT(*) FROM scheduled_posts WHERE status = 'failed' AND created_at > NOW() - (period_days || ' days')::INTERVAL)::DECIMAL / 
          (SELECT COUNT(*) FROM scheduled_posts WHERE created_at > NOW() - (period_days || ' days')::INTERVAL) * 100, 2
        )
        ELSE 0
      END
    ),
    'active_sources', (SELECT COUNT(*) FROM categories WHERE is_active = true)
  ) INTO result;
  
  RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Comentarios para documentación
COMMENT ON TABLE profiles IS 'Perfiles de usuario extendidos desde auth.users';
COMMENT ON TABLE categories IS 'Categorías de noticias y fuentes de datos';
COMMENT ON TABLE linkedin_profiles IS 'Perfiles de LinkedIn conectados por usuario';
COMMENT ON TABLE news IS 'Noticias recolectadas de fuentes externas';
COMMENT ON TABLE scheduled_posts IS 'Publicaciones programadas para LinkedIn';
COMMENT ON TABLE audits IS 'Logs de auditoría del sistema';
